// <auto-generated />
namespace insitum.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CREANDO_CAMPO_ESTADO_USUARIO : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CREANDO_CAMPO_ESTADO_USUARIO));
        
        string IMigrationMetadata.Id
        {
            get { return "201807032210402_CREANDO_CAMPO_ESTADO_USUARIO"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
