// <auto-generated />
namespace insitum.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class agregandofechaFin_DetalleFin_Estado_Acciones : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(agregandofechaFin_DetalleFin_Estado_Acciones));
        
        string IMigrationMetadata.Id
        {
            get { return "201807161715275_agregandofechaFin_DetalleFin_Estado_Acciones"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
